package com.stranger.easyfindboot.mapper;

import com.stranger.easyfindboot.entity.SysRoleRight;
import com.stranger.easyfindboot.entity.SysRoleRightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    long countByExample(SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    int deleteByExample(SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    int insert(SysRoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    int insertSelective(SysRoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    List<SysRoleRight> selectByExample(SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRoleRight record, @Param("example") SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_right
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    int updateByExample(@Param("record") SysRoleRight record, @Param("example") SysRoleRightExample example);
}