package com.stranger.easyfindboot.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_right_menu
 */
public class SysRightMenu {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_menu.id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_menu.right_id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Long rightId;

    /**
     * Database Column Remarks:
     *   菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_menu.menu_id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Long menuId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_menu.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_menu.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_menu.id
     *
     * @return the value of sys_right_menu.id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_menu.id
     *
     * @param id the value for sys_right_menu.id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_menu.right_id
     *
     * @return the value of sys_right_menu.right_id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_menu.right_id
     *
     * @param rightId the value for sys_right_menu.right_id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_menu.menu_id
     *
     * @return the value of sys_right_menu.menu_id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_menu.menu_id
     *
     * @param menuId the value for sys_right_menu.menu_id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_menu.gmt_create
     *
     * @return the value of sys_right_menu.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_menu.gmt_create
     *
     * @param gmtCreate the value for sys_right_menu.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_menu.gmt_modified
     *
     * @return the value of sys_right_menu.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_menu.gmt_modified
     *
     * @param gmtModified the value for sys_right_menu.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}