package com.stranger.easyfindboot.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_right
 */
public class SysRight {
    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.menu_type
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private String menuType;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.id
     *
     * @return the value of sys_right.id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.id
     *
     * @param id the value for sys_right.id
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.menu_type
     *
     * @return the value of sys_right.menu_type
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.menu_type
     *
     * @param menuType the value for sys_right.menu_type
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.gmt_create
     *
     * @return the value of sys_right.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.gmt_create
     *
     * @param gmtCreate the value for sys_right.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.gmt_modified
     *
     * @return the value of sys_right.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.gmt_modified
     *
     * @param gmtModified the value for sys_right.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:25 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}