package com.stranger.easyfindboot.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_right
 */
public class SysRoleRight {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_right.id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_right.role_id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_right.right_id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    private Long rightId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_right.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_right.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_right.id
     *
     * @return the value of sys_role_right.id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_right.id
     *
     * @param id the value for sys_role_right.id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_right.role_id
     *
     * @return the value of sys_role_right.role_id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_right.role_id
     *
     * @param roleId the value for sys_role_right.role_id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_right.right_id
     *
     * @return the value of sys_role_right.right_id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_right.right_id
     *
     * @param rightId the value for sys_role_right.right_id
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_right.gmt_create
     *
     * @return the value of sys_role_right.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_right.gmt_create
     *
     * @param gmtCreate the value for sys_role_right.gmt_create
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_right.gmt_modified
     *
     * @return the value of sys_role_right.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_right.gmt_modified
     *
     * @param gmtModified the value for sys_role_right.gmt_modified
     *
     * @mbg.generated Thu Mar 19 08:59:24 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}